#+title: Note

* Chapter 8 - Statement and State
** Exercise 3
It work as expected, and also behave as in many other language.
It is untuitive that the right hand side is evaluated before the left hand side, so the ~a + 2~ use the ~a~ from outer env and bind to ~a~ in the inner env.
The print statement use the ~a~ from the inner/local env.

* Chapter 9 - Control flow
I've made some mistake in the past and picking up the project after a couple of months I was not able to find the mistake, hence I copied a version that work up to chapter 9 (if you ever see this, thanks [[https://github.com/Silvernitro/jlox.git][Silvernitro]]).
** Exercise 1
You can create control flow with dynamic dispatch, it is a little bit clumsy and not so much readable.
So if you ever want to create a programming language without branching statements, please, keep it to yourself.
To complete the answer we can define methods that act as =if= and =else= based on the type.
To make it feasible we can make /one method/ that accept our concept of =truth= and another that accept =falsiness= (of course both should be able to accept a code block).
** Exercise 2
Dynamic dispatch is far more slower than branching hence we need our, hypothetical, language need to be optimized for dynamic dispatch.
I can't name a language that use this concept for iteration but I can made some guesses:
+ =ruby=, it support /traditional/ loops, but it can also be implemented with objects.
+ =smalltalk, pharo=, in such languages I've heard that everything (even more than java) is an object.
+ =java=, in particular with =stream= (i.e. =IntStream=) you can write loop in an object oriented way (to me streams doesn't seem to functionals).
** Exercise 3
Add =break= instruction.

* Chapter 10 - Functions
** Exercise 1
Because in smalltalk everything is an object, hence if you create a function you have a constructor with a predetermined number of argument.
If you call such a function with the wrong number it won't compile.
** Exercise 2
Add anonymous function.
** Exercise 3
#+begin_src lox
fun scope(a) {
  var a = "local";
}
#+end_src
Of course it is a valid /lox/ script.
When a function is defined the paramters are binded to the function environment.
Subsequently the rest of the instruction override the local env.
For me a language should do what /lox/ is doing, allow the code and use the innermost definition in the function body.
Some exception can be made for functional language, but not by much.

* Chapter 11 - Resolving and binding
From now on I will not implement the exercise like /implement ?:/, /implement break/, they stack up adding more complexity at each chapter, instead I will provide a desccription of how I will proceed.
** Exercise 1
A function only need to be defined, instead an initializer need to be executed before we know the value to associate to the variable.
** Exercise 2
All the ones I can think about will allow such definition, to me make quite sense.
I want to initialize =a=, to initialize =a= I need to access =a=, but it is defined outside the scope, hence the expression on the right refer to the outer (global) =a=.
** Exercise 3
After the =resolve= method I will check if every variable defined is accessed, even through the map I already have or through another one.
Maybe an array that count the references in the blocks to each variable (except definition and initialization), if it is $1$ then there is an /error/.
** Exercise 4
Pretty simple, provided an =ArrayList= and a =BigInteger= generator the request is pretty trivial, I just need to add an index to the variables fields.
