// AUTOGENERATED CLASS
package com.craftinginterpreters.lox;

public record Binary(Expr left, Token operator, Expr right) implements Expr {

	@Override
	public <T> T accept(Expr.Visitor<T> visitor) {
		return visitor.visitBinaryExpr(this);
	}
}