// AUTOGENERATED CLASS
package com.craftinginterpreters.lox;

public sealed interface Expr permits Binary, Grouping, Literal, Unary {
	public interface Visitor<T> {
		public T visitBinaryExpr(Binary expr);
		public T visitGroupingExpr(Grouping expr);
		public T visitLiteralExpr(Literal expr);
		public T visitUnaryExpr(Unary expr);
	}

	public static <T> T accept(Visitor<T> visitor, Expr expr) {
		 return switch(expr) {
			case Binary e -> visitor.visitBinaryExpr(e);
			case Grouping e -> visitor.visitGroupingExpr(e);
			case Literal e -> visitor.visitLiteralExpr(e);
			case Unary e -> visitor.visitUnaryExpr(e);
		};
	}
}