// AUTOGENERATED CLASS
package com.craftinginterpreters.lox;

public sealed interface Expr permits Binary, Grouping, Literal, Unary {
	public interface Visitor<T> {
		public T visitBinaryExpr(Binary expr);
		public T visitGroupingExpr(Grouping expr);
		public T visitLiteralExpr(Literal expr);
		public T visitUnaryExpr(Unary expr);
	}

	<T> T accept(Visitor<T> visitor);

}