// AUTOGENERATED CLASS
package com.craftinginterpreters.lox;

public record Grouping(Expr expression) implements Expr {

	@Override
	public <T> T accept(Expr.Visitor<T> visitor) {
		return visitor.visitGroupingExpr(this);
	}
}