// AUTOGENERATED CLASS
package com.craftinginterpreters.lox;

public record Literal(LoxValue value) implements Expr {

	@Override
	public <T> T accept(Expr.Visitor<T> visitor) {
		return visitor.visitLiteralExpr(this);
	}
}