// AUTOGENERATED CLASS
package com.craftinginterpreters.lox;

public record Unary(Token operator, Expr right) implements Expr {

	@Override
	public <T> T accept(Expr.Visitor<T> visitor) {
		return visitor.visitUnaryExpr(this);
	}
}